### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-2-romanet-tournier#1]
⚠️ Etrange d'ajouter une méthode à chaque fois qu'on veut ajouter un Visitor non ? Moi ça me parait bizarre.On avait pas dit que le visitor ça servait à ça? Je suis sur que vous pouvez trouver une solution.

⚠️ Au niveau du calcul vous êtes sur de respecter les priorités des opérateurs ?

👎 L'uml il est bien hein... mais c'est dommage on voit pas la partie Visiteur., vous pourriez pas m'en faire un avec toutes les classes dedans ?

**Comment by RomanetAdrien** [comment]
On ne comprends pas ce que tu veux dire pour la priorité des opérateurs, on a essayé avec d'autres arbres  en plus de l'arbre de base et ça fonctionnait encore donc on ne voit pas où est le problème.

**Comment by Slashgear** [comment]
Sorry d'être passé à coté de ton message, rien de grave sur la priorité 😉 

Sinon c'est good 👍
